image: dbones/monocore:1.1-2.0-sdk

pipelines:
  default:
  
    - step:
        name: build
        script:
          - cd src
          - dotnet restore
          - msbuild /target:Build /p:Configuration=Release /p:BuildNumber=$BITBUCKET_BUILD_NUMBER
        artifacts: # defining the artifacts to be passed to each future step.
          - src/**

    - parallel:
        - step:
            name: test
            script:
              - pwd
              - cd src
              - dotnet test --no-build --configuration Release
            services:
              - document

        - step:
            name: package
            script:
              - pwd
              - cd src
              - dotnet pack --no-build --configuration Release --output ../nupkgs

    - step:
        deployment: production
        name: Deploy to test
        trigger: manual
        script:
          - echo "Deploying to test environment"
          - pwd
          - cd src -k $
          - dotnet nuget push $NUGET

definitions:
  services:
    document:
      image: couchdb
